version: 2

project_name: hawkeye

builds:
  - binary: hawkeye
    main: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "{{ .ProjectName }}-{{ .Version }}-checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch

homebrew_casks:
  - name: neubird-hawkeye
    binaries:
      - hawkeye
    repository:
      owner: neubirdai
      name: homebrew-hawkeye
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Casks
    homepage: "https://github.com/neubirdai/hawkeye-cli"
    description: "AI-powered incident investigation CLI for Neubird Hawkeye"

dockers_v2:
  - images:
      - "neubirdai/hawkeye-cli"
    tags:
      - "v{{ .Version }}"
      - latest
    platforms:
      - linux/amd64
      - linux/arm64
    disable: "{{ .IsSnapshot }}"

snapcrafts:
  - name: hawkeye-cli
    summary: AI-powered SRE incident investigation CLI
    description: |
      Hawkeye CLI is a command-line client for the Neubird Hawkeye AI SRE platform.
      It enables AI-powered incident investigations with real-time SSE streaming,
      interactive session management, and chain-of-thought reasoning visualization.
    grade: stable
    confinement: strict
    license: MIT
    apps:
      hawkeye-cli:
        command: hawkeye
        plugs:
          - network
          - home

nfpms:
  - package_name: hawkeye-cli
    vendor: Neubird AI
    homepage: "https://github.com/neubirdai/hawkeye-cli"
    maintainer: "Neubird AI <support@neubird.com>"
    description: "AI-powered incident investigation CLI for Neubird Hawkeye"
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin

release:
  github:
    owner: neubirdai
    name: hawkeye-cli
  draft: false
  prerelease: auto
  mode: replace
