version: 2

project_name: hawkeye

before:
  hooks:
    - go mod tidy
    - go test ./... -count=1

builds:
  - id: hawkeye
    main: .
    binary: hawkeye
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: neubirdai
    name: hawkeye-cli
  draft: false
  prerelease: auto
  name_template: "{{.Tag}}"

brews:
  - name: neubird-hawkeye
    repository:
      owner: neubirdai
      name: homebrew-hawkeye
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://neubird.com"
    description: "AI-powered SRE incident investigation CLI for Neubird Hawkeye"
    license: "MIT"
    install: |
      bin.install "hawkeye"
    test: |
      system "#{bin}/hawkeye", "help"

dockers:
  - image_templates:
      - "neubirdai/hawkeye-cli:{{ .Tag }}-amd64"
      - "ghcr.io/neubirdai/hawkeye-cli:{{ .Tag }}-amd64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
    goarch: amd64

  - image_templates:
      - "neubirdai/hawkeye-cli:{{ .Tag }}-arm64"
      - "ghcr.io/neubirdai/hawkeye-cli:{{ .Tag }}-arm64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
    goarch: arm64

docker_manifests:
  - name_template: "neubirdai/hawkeye-cli:{{ .Tag }}"
    image_templates:
      - "neubirdai/hawkeye-cli:{{ .Tag }}-amd64"
      - "neubirdai/hawkeye-cli:{{ .Tag }}-arm64"

  - name_template: "neubirdai/hawkeye-cli:latest"
    image_templates:
      - "neubirdai/hawkeye-cli:{{ .Tag }}-amd64"
      - "neubirdai/hawkeye-cli:{{ .Tag }}-arm64"

  - name_template: "ghcr.io/neubirdai/hawkeye-cli:{{ .Tag }}"
    image_templates:
      - "ghcr.io/neubirdai/hawkeye-cli:{{ .Tag }}-amd64"
      - "ghcr.io/neubirdai/hawkeye-cli:{{ .Tag }}-arm64"

  - name_template: "ghcr.io/neubirdai/hawkeye-cli:latest"
    image_templates:
      - "ghcr.io/neubirdai/hawkeye-cli:{{ .Tag }}-amd64"
      - "ghcr.io/neubirdai/hawkeye-cli:{{ .Tag }}-arm64"

snapcrafts:
  - name: hawkeye-cli
    summary: AI-powered SRE incident investigation CLI
    description: |
      Hawkeye CLI is a command-line client for the Neubird Hawkeye AI SRE platform.
      It enables AI-powered incident investigations with real-time SSE streaming,
      interactive session management, and chain-of-thought reasoning visualization.
    grade: stable
    confinement: strict
    license: MIT
    apps:
      hawkeye-cli:
        command: hawkeye
        plugs:
          - network
          - home

nfpms:
  - package_name: hawkeye-cli
    vendor: Neubird AI
    homepage: "https://github.com/neubirdai/hawkeye-cli"
    maintainer: "Neubird AI <support@neubird.com>"
    description: "AI-powered incident investigation CLI for Neubird Hawkeye"
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
